name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish to Github Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: zann1x/zann1x.github.io
        # Git branch where assets will be deployed
        target_branch: master
        # Build directory to deploy
        build_dir: public
        # Create incremental commit instead of doing push force
        keep_history: false
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
