name: CI

# Controls when the action will run.
# Triggers the workflow on push events on the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install npm dependencies
      run: npm ci

    # Runs a set of commands using the runners shell
    - name: Build the static site
      run: |
        echo Starting the build...
        npm run build
        echo Finished building

    - name: Publish to Github Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: https://github.com/zann1x/zann1x.github.io
        # Git branch where assets will be deployed
        target_branch: master
        # Build directory to deploy
        build_dir: public
        # The author name and email address
        author: Lukas Zanner <git@lukaszanner.de>
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
